CC=i686-w64-mingw32-gcc
CFLAGS= -Wall -O5 -Wno-overflow
PROGS= hid-mouse

all:	${PROGS}

hid-mouse:	usbip.c hid-mouse.c 
		${CC} ${CFLAGS} usbip.c -c 
		${CC} ${CFLAGS} usbip.o hid-mouse.c -o hid-mouse.exe -lws2_32 

clean:
		rm -f ${PROGS} core core.* *.o temp.* *.out typescript* *.exe
